const {createClient}=supabase;
const db=createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
const grid=document.getElementById("productGrid"),status=document.getElementById("status"),search=document.getElementById("searchInput"),filter=document.getElementById("categoryFilter"),shareDialog=document.getElementById("shareDialog");
let products=[];
const money=v=>"৳"+Number(v||0).toLocaleString("bn-BD");
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const mediaList=(value,legacy)=>Array.isArray(value)&&value.length?value:(legacy?[legacy]:[]);
const productUrl=p=>{const url=new URL(window.location.href);url.hash=`product=${encodeURIComponent(p.id)}`;return url.href};
const whatsappUrl=p=>`https://wa.me/${window.WHATSAPP_NUMBER}?text=${encodeURIComponent(`Hello, I am interested in purchasing ${p.name}.`)}`;
const applyTheme=theme=>{document.body.setAttribute("data-theme",theme);localStorage.setItem("theme",theme);const btn=document.getElementById("themeToggle");if(btn)btn.textContent=theme==="dark"?"☀️":"🌙"};
applyTheme(localStorage.getItem("theme")||(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"));
document.getElementById("themeToggle")?.addEventListener("click",()=>applyTheme(document.body.getAttribute("data-theme")==="dark"?"light":"dark"));
function render(){const q=search.value.toLowerCase().trim(),c=filter.value;const visible=products.filter(p=>(!q||(`${p.name} ${p.description||""}`).toLowerCase().includes(q))&&(!c||p.category===c));grid.innerHTML=visible.length?visible.map(p=>{const images=mediaList(p.image_urls,p.image_url),videos=mediaList(p.video_urls),media=images.map(url=>`<img src="${esc(url)}" alt="${esc(p.name)}" loading="lazy">`).join("")+videos.map(url=>`<video src="${esc(url)}" controls preload="metadata"></video>`).join("");const qty=Number(p.quantity||0);return `<article class="card" id="product-${esc(p.id)}"><div class="pic">${media||`<img src="assets/product-placeholder.svg" alt="No image">`}</div><div class="body"><small>${esc(p.category||"Others")}</small><h3>${esc(p.name)}</h3><div class="description collapsed" data-description>${esc(p.description||"")}</div>${p.description&&p.description.length>100?`<button class="textButton" data-more>See More</button>`:""}${qty>0?`<p class="stock in-stock">In stock: ${qty}</p>`:`<p class="stock out-of-stock">Out of stock</p>`}<strong>${money(p.price)}</strong>${p.old_price?` <del>${money(p.old_price)}</del>`:""}<div class="cardActions"><a class="btn whatsapp" href="${whatsappUrl(p)}" target="_blank" rel="noopener">Buy on WhatsApp</a><button class="btn share" data-share="${esc(p.id)}">Share</button></div><small class="contactNumber">WhatsApp: +${esc(window.WHATSAPP_NUMBER)}</small></div></article>`}).join(""):"<div class='empty'>No products found.</div>"}
async function shareProduct(p){const url=productUrl(p),data={title:p.name,text:`I am interested in ${p.name}`,url};if(navigator.share){try{await navigator.share(data);return}catch(error){if(error.name==="AbortError")return}}const encodedUrl=encodeURIComponent(url),text=encodeURIComponent(`I am interested in ${p.name} ${url}`);shareDialog.innerHTML=`<div class="sharePanel"><button class="shareClose" data-close aria-label="Close">×</button><strong>Share ${esc(p.name)}</strong><div class="shareOptions"><a target="_blank" rel="noopener" href="https://wa.me/?text=${text}">WhatsApp</a><a target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}">Facebook</a><a target="_blank" rel="noopener" href="https://t.me/share/url?url=${encodedUrl}&text=${encodeURIComponent(p.name)}">Telegram</a><button data-copy="${esc(url)}">Copy Link</button></div><p id="copyStatus"></p></div>`;shareDialog.classList.remove("hidden")}
grid.addEventListener("click",async event=>{const more=event.target.closest("[data-more]");if(more){const description=more.previousElementSibling;description.classList.toggle("collapsed");more.textContent=description.classList.contains("collapsed")?"See More":"See Less";return}const share=event.target.closest("[data-share]");if(share){const product=products.find(item=>item.id===share.dataset.share);if(product)await shareProduct(product)}});
shareDialog?.addEventListener("click",async event=>{if(event.target.closest("[data-close]")){shareDialog.classList.add("hidden");return}const copy=event.target.closest("[data-copy]");if(copy){try{await navigator.clipboard.writeText(copy.dataset.copy);document.getElementById("copyStatus").textContent="Link copied"}catch(error){document.getElementById("copyStatus").textContent="Copy failed; select the link manually."}}});
async function loadLogo(){const {data}=await db.from("site_settings").select("logo_url").eq("id",true).maybeSingle();if(data?.logo_url){document.querySelectorAll("#siteLogo").forEach(image=>{image.src=data.logo_url;image.style.display="block"});const hero=document.querySelector(".heroCard");if(hero)hero.style.backgroundImage=`url("${data.logo_url}")`}}
async function load(){if(!window.SUPABASE_URL||window.SUPABASE_URL.includes("PASTE_")){status.textContent="Add your Supabase details in config.js.";return}const {data,error}=await db.from("products").select("*").order("created_at",{ascending:false});if(error){status.textContent="Products could not be loaded right now.";return}products=data||[];status.textContent=products.length?"":"No products have been added yet.";render();loadLogo()}
search.oninput=render;filter.onchange=render;document.querySelectorAll("[data-category]").forEach(x=>x.onclick=()=>{filter.value=x.dataset.category;document.getElementById("shop").scrollIntoView({behavior:"smooth"});render()});document.getElementById("year").textContent=new Date().getFullYear();document.getElementById("menuBtn").onclick=()=>document.getElementById("mainNav").classList.toggle("open");load();
