-- প্রথমে Authentication > Users-এ sayfulnws@gmail.com user তৈরি করুন।
create table if not exists public.products(id bigint generated by default as identity primary key,name text not null,price numeric(12,2) not null,old_price numeric(12,2),category text not null default 'মুদি পণ্য',description text,image_url text,storage_path text,featured boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz not null default now());
insert into public.admin_users(user_id) select id from auth.users where email='sayfulnws@gmail.com' on conflict(user_id) do nothing;
create or replace function public.is_admin() returns boolean language sql security definer stable set search_path=public as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()); $$;
grant execute on function public.is_admin() to authenticated;
alter table public.products enable row level security;
drop policy if exists "view products" on public.products;drop policy if exists "admin insert products" on public.products;drop policy if exists "admin update products" on public.products;drop policy if exists "admin delete products" on public.products;
create policy "view products" on public.products for select to anon,authenticated using(true);
create policy "admin insert products" on public.products for insert to authenticated with check(public.is_admin());
create policy "admin update products" on public.products for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admin delete products" on public.products for delete to authenticated using(public.is_admin());
grant select on public.products to anon,authenticated;grant insert,update,delete on public.products to authenticated;
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do nothing;
drop policy if exists "view product images" on storage.objects;drop policy if exists "admin upload images" on storage.objects;drop policy if exists "admin update images" on storage.objects;drop policy if exists "admin delete images" on storage.objects;
create policy "view product images" on storage.objects for select to public using(bucket_id='product-images');
create policy "admin upload images" on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.is_admin());
create policy "admin update images" on storage.objects for update to authenticated using(bucket_id='product-images' and public.is_admin()) with check(bucket_id='product-images' and public.is_admin());
create policy "admin delete images" on storage.objects for delete to authenticated using(bucket_id='product-images' and public.is_admin());